### ISSUE TITLE
Archives version ordering is contrary to what most people expect

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [Legend-of-iPhoenix/cemetech-userstyle#14]
![unknown](https://user-images.githubusercontent.com/32944537/102382643-a7ef7880-3f98-11eb-8761-913b982e1065.png)
Ideally, it would go 4, 3, 2, 1 in the above image.

**Comment by Legend-of-iPhoenix** [comment]
An alternative option is reversing the chronology so that the oldest one is on top- I'm not sure if this is better or worse. 

My concern is that it could be a bit jarring to see a list counting down. I'll do the newest-on-top reversed-numbering method and if people complain it's trivial to do it the alternative option.

**Comment by tari** [comment]
While developing this I tried reversed numbering and it seemed very weird. The newest version is on top because that's typically the one you care about most.

**Comment by Legend-of-iPhoenix** [comment]
I figured as much- it seems to me like there's no really good way to do this that doesn't involve some form of compromise. Perhaps using something meaningful like the upload date instead of arbitrary consecutive numbers would be less jarring.
