### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [Legend-of-iPhoenix/cemetech-userstyle#15]
Installing the extension on firefox is quite sucky- there has to be a better way!

**Comment by Eeems** [comment]
https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

**Comment by Legend-of-iPhoenix** [comment]
gently modified #cemetech logs

---

iPhoenix: oh nice I got the sax rewrite to work on firefox
fghsgh: \o/
iPhoenix: I hate firefox's browser extension system
iPhoenix: like, with chrome stuff just works?
iPhoenix: firefox is the reason I have to write code like this `const runtime = chrome === undefined ? (browser === undefined ? undefined : browser.extension) : chrome.runtime;`
iPhoenix: anyways, because firefox is dumb, you can't actually permanently load that even if you try really hard to
iPhoenix: I have to have firefox review my code to make sure it's up to their standards, and then you are allowed to install it (even if I don't share it publicly)
fghsgh: well it's better than letting anyone into their extension store if they want
iPhoenix: yes, but I have to do this even if I don't want to go into their extension store
iPhoenix: that's what's infuriating to me
iPhoenix: protecting their extension store is extremely sensible, and also something I would do
fghsgh: well waterfox doesn't need it in any case
iPhoenix: :D
iPhoenix: looks like firefox doesn't load content scripts as well as chrome either
iPhoenix: (causing a major distracting layout shift after the page loads)

## iPhoenix: **even though all of the code I write in the extension itself will have good compatibility, I don't plan to add firefox support at this time because of the reasons previously outlined :)**

**Comment by Eeems** [comment]
> because firefox is dumb

No u

>  I have to have firefox review my code to make sure it's up to their standards, and then you are allowed to install it (even if I don't share it publicly)

Not too big of a deal. I've already done this in the past and had no issues. Usually it's an automatic process:
![image](https://user-images.githubusercontent.com/1176979/104934429-59524700-5967-11eb-82a5-b014c470e215.png)


> iPhoenix: **even though all of the code I write in the extension itself will have good compatibility, I don't plan to add firefox support at this time because of the reasons previously outlined :)**

I guess it's up so someone else to port it then?


> iPhoenix: looks like firefox doesn't load content scripts as well as chrome either
> iPhoenix: (causing a major distracting layout shift after the page loads)

https://discourse.mozilla.org/t/modify-a-web-page-before-displaying-it-webextensions/16002 You just aren't loading your scripts at the right place.

**Comment by Eeems** [comment]
>
> iPhoenix: firefox is the reason I have to write code like this `const runtime = chrome === undefined ? (browser === undefined ? undefined : browser.extension) : chrome.runtime;`

I don't see you using chrome or runtime in your code?
