### ISSUE TITLE
How to minify/package

### ISSUE THREAD

**Issue by mateoconlechuga** [Legend-of-iPhoenix/cemetech-userstyle#19]
How do I minify/package?

**Comment by Legend-of-iPhoenix** [comment]
Extension code is loaded from your computer (fast) instead of over network (slow), so there's no benefit at all from doing this.

**Comment by Legend-of-iPhoenix** [comment]
If you really need it in one file for some reason just `cat src/*.js > all.js` and there's your packaged js file

**Comment by mateoconlechuga** [comment]
But how do I minify?

**Comment by adriweb** [comment]
probably with a minifier

**Comment by mateoconlechuga** [comment]
what's that

**Comment by KryptonicDragon** [comment]
It's like one of those emails that promises to enlarge stuff for you, but the opposite

**Comment by Legend-of-iPhoenix** [comment]
https://developers.google.com/closure/compiler
https://github.com/terser/terser
but still there's no point for an extension

I'm really, really confused about why you want this.

**Comment by adriweb** [comment]
Yeah closure compiler is good (online version https://closure-compiler.appspot.com/home )
