### ISSUE TITLE
<main> width preserved when resizing & <aside> spacing

### ISSUE THREAD

**Issue by LogicalJoe** [Legend-of-iPhoenix/cemetech-userstyle#4]
1. Probably already on the todo list, but making the window small enough that the `<asides>` relocate themselves does not cause `<main>` to resize to fill the screen.
![tinytech](https://user-images.githubusercontent.com/47825483/93038344-bd0fe080-f612-11ea-8d86-834290a06f43.png)[Safari 14607.2.6.1.1]

2. May or may not be fixable, but Mateo's /p287497 of /t16887 (deleted) said that the gap between the [Logged In] and [Online Users] is bigger than the other gaps because they are in separate `<aside>`'s.

**Comment by Legend-of-iPhoenix** [comment]
1. Yes, I'll fix this before releasing 2.1
2. That is correct. I fixed it with some CSS- see https://github.com/Legend-of-iPhoenix/cemetech-userstyle/blob/88b103b1ff6156e8d1409fea664918a9ccc144aa/userstyle.css#L150-L153
